name             'flexget'
maintainer       'The Authors'
maintainer_email 'gsreynolds@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures FlexGet'
long_description 'Installs/Configures FlexGet'
version          '0.1.3'

depends 'python'
depends 'cron'
